import * as api from "../api";
import {
  OPERATION_USER_BEGIN,
  REGISTER_USER_OK,
  REGISTER_USER_ERROR,
  LOGIN_USER_OK,
  LOGIN_USER_ERROR,
  LOGOUT_USER,
  GET_IMAGES_OK,
  GET_IMAGES_FAILED,
  WAITING_TO_FETCH,
  CREATE_IMAGE_OK,
  CREATE_IMAGE_FAILED,
  UPDATE_IMAGE_OK,
  UPDATE_IMAGE_FAILED,
  GET_ONE_IMAGE_OK,
  GET_ONE_IMAGE_FAILED,
  DELETE_IMAGE_OK,
} from "../constants/actionTypes";
