export const WAITING_TO_GET = "WAITING_TO_GET";
export const DATA_FETCHED = "DATA_FETCHED";
export const GET_ALL = "GET_ALL";

export const OPERATION_USER_BEGIN = "OPERATION_USER_BEGIN";
export const REGISTER_USER_OK = "REGISTER_USER_OK";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER_OK = "LOGIN_USER_OK";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_IMAGE_OK = "CREATE_IMAGE_OK";
export const CREATE_IMAGE_FAILED = "CREATE_IMAGE_FAILED";
export const GET_IMAGES_OK = "GET_IMAGES_OK";
export const GET_IMAGES_FAILED = "GET_IMAGES_FAILED";
export const DELETE_IMAGE_OK = "DELETE_IMAGE_OK";
export const SET_UPDATE_IMAGE = "SET_UPDATE_IMAGE";
export const PREPARE_TO_UPDATE = "PREPARE_TO_UPDATE";
export const UPDATE_IMAGE_OK = "UPDATE_IMAGE_OK";
export const UPDATE_IMAGE_FAILED = "UPDATE_IMAGE_FAILED";
export const GET_ONE_IMAGE_OK = "GET_ONE_IMAGE_OK";
export const GET_ONE_IMAGE_FAILED = "GET_ONE_IMAGE_FAILED";
